{% set version = "0.7.17" %}
{% set sha256 = "b96635fe965c1b3a42eaa8510d7a0eb25de56c3782aa9bd1d681afaf286df3fe" %}

package:
  name: bwa
  version: {{ version }}

source:
  url: https://github.com/zamaudio/bwa/archive/intel-extend-0.7.17.zip
  sha256: {{ sha256 }}
  patches:
    - my.patch # the patch file is expected to be found in the recipe

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
  run:
    - zlib
    - perl

test:
  commands:
    - bwa 2>&1 | grep "index sequences in the"
    - which xa2multi.pl
    - which qualfa2fq.pl

about:
  home: https://github.com/lh3/bwa
  license: GPL3
  summary: The BWA read mapper.

extra:
  identifiers:
    - biotools:bwa
